---
apiVersion: v1
kind: Service
metadata:
  name: arrayCalculator
  labels:
    app: arrayCalculator
spec:
  type: NodePort
  selector:
    app: arrayCalculator
  ports:
    - protocol: TCP
      port: 8888
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: arrayCalculator
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: arrayCalculator
    spec:
      containers:
        - name: arrayCalculator
          image: webberlh/array-calculator
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: /metric
              port: 8888
            initialDelaySeconds: 30
            timeoutSeconds: 1