---
apiVersion: v1
kind: Service
metadata:
  name: array-calculator
  labels:
    app: array-calculator
spec:
  type: NodePort
  selector:
    app: array-calculator
  ports:
    - protocol: TCP
      port: 8888
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: array-calculator
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: array-calculator
    spec:
      schedulerName: extended-default-scheduler
      containers:
        - name: array-calculator
          image: 10.0.0.100:5000/webberlh/array-calculator:latest
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: /metric
              port: 8888
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 20